  version: '3.8'

  services:
    mysql:
      image: mysql:8.0
      container_name: mysql-container
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: restdb
        MYSQL_USER: restadmin
        MYSQL_PASSWORD: password
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - mysql_data:/var/lib/mysql

  volumes:
    mysql_data: